server:
  port: 3000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backend_media
    username: postgres
    password: Trustno1
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
